# Generated by Django 5.0.3 on 2024-03-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='ph_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userID',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
