# Generated by Django 5.0.3 on 2024-03-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userdetails_ph_no_alter_userdetails_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userID',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
