# Generated by Django 5.0.3 on 2024-03-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userdetails_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userID',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
