// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9uP0IRvOKwub5827gU7e1Nb2rOa81PwA',
    appId: '1:977257696058:web:5c6d54ab4cd17aa7725e03',
    messagingSenderId: '977257696058',
    projectId: 'zorko-16437',
    authDomain: 'zorko-16437.firebaseapp.com',
    storageBucket: 'zorko-16437.appspot.com',
    measurementId: 'G-SRRPSXPLGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAd9P4rt9SHYb1NVoF68tUg1OPDig1zWE',
    appId: '1:977257696058:android:422df49b144360b9725e03',
    messagingSenderId: '977257696058',
    projectId: 'zorko-16437',
    storageBucket: 'zorko-16437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByMjN-UzWNaGxl_nSdVFjhbu2poCOlBP4',
    appId: '1:977257696058:ios:df49ab278da1a77c725e03',
    messagingSenderId: '977257696058',
    projectId: 'zorko-16437',
    storageBucket: 'zorko-16437.appspot.com',
    iosBundleId: 'com.example.zorko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByMjN-UzWNaGxl_nSdVFjhbu2poCOlBP4',
    appId: '1:977257696058:ios:602128580843ac1a725e03',
    messagingSenderId: '977257696058',
    projectId: 'zorko-16437',
    storageBucket: 'zorko-16437.appspot.com',
    iosBundleId: 'com.example.zorko.RunnerTests',
  );
}
